import {
  siReact,
  siNodedotjs,
  siExpress,
  siMysql,
  siSupabase,
  siTailwindcss,
  siTypescript,
  siNextdotjs,
  siOpenjdk,
  siSpringboot,
  siRedis,
  siDocker,
  siGit,
  siFigma,
  siVercel,
  siPostgresql,
  siMongodb,
  siCursor,
  siPostman,
  siDbeaver,
  siAppwrite,
  siPrisma,
  siDotnet,
  siEthereum,
  siGraphql,
  siFramer,
  siThreedotjs,
  siPostcss,
  siEslint,
  siPrettier,
  siApachekafka,
  siLinux,
  siJetbrains,
  siNeovim,
  siDjango,
  siFlask,
  siFastify,
  siGithub,
  siVite,
  siJavascript,
  siCss,
  siBootstrap,
  siGithubactions,
  siNetlify,
  siCloudflare,
  siClaude,
  siAnthropic,
  siNotion,
  siObsidian,
  siPython,
  siHtml5,
  siFirebase,
  siLeetcode,
  siTryhackme,
  siLaravel,
  siPhp,
} from "simple-icons";

/**
 * Genuine brand marks, one consistent treatment: a single-colour path that
 * inherits the surrounding text colour, so a row of them reads as one set
 * rather than a pile of clip art. Anything without a real mark is left out
 * and rendered as its name instead. Nothing here is invented or approximated.
 */
const REGISTRY: Record<string, { path: string }> = {
  react: siReact,
  "node.js": siNodedotjs,
  express: siExpress,
  mysql: siMysql,
  supabase: siSupabase,
  "tailwind css": siTailwindcss,
  typescript: siTypescript,
  "next.js": siNextdotjs,
  java: siOpenjdk,
  "spring boot": siSpringboot,
  redis: siRedis,
  docker: siDocker,
  git: siGit,
  figma: siFigma,
  vercel: siVercel,
  postgresql: siPostgresql,
  mongodb: siMongodb,
  cursor: siCursor,
  postman: siPostman,
  dbeaver: siDbeaver,
  appwrite: siAppwrite,
  prisma: siPrisma,
  ".net": siDotnet,
  ethereum: siEthereum,
  graphql: siGraphql,
  framer: siFramer,
  "three.js": siThreedotjs,
  postcss: siPostcss,
  eslint: siEslint,
  prettier: siPrettier,
  kafka: siApachekafka,
  linux: siLinux,
  jetbrains: siJetbrains,
  neovim: siNeovim,
  django: siDjango,
  flask: siFlask,
  fastify: siFastify,
  github: siGithub,
  vite: siVite,
  javascript: siJavascript,
  css: siCss,
  bootstrap: siBootstrap,
  "github actions": siGithubactions,
  netlify: siNetlify,
  cloudflare: siCloudflare,
  claude: siClaude,
  anthropic: siAnthropic,
  notion: siNotion,
  obsidian: siObsidian,
  python: siPython,
  html: siHtml5,
  firebase: siFirebase,
  leetcode: siLeetcode,
  tryhackme: siTryhackme,
  laravel: siLaravel,
  php: siPhp,
};

/** Look up a real mark path by tech name. Null when there is no honest mark. */
export function brandPath(name: string): string | null {
  return REGISTRY[name.trim().toLowerCase()]?.path ?? null;
}
